name: Publish Python package to PyPI

on:
  push:
    tags:
      - v[0-9]*
  release:
    types:
      - published

jobs:
  build-publish:
    name: Build and publish Python package
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user

      - name: Build a wheel and source distribution
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/

      - name: Publish to TestPyPI
        if: ${{ github.event.action != 'published' }}
        uses: pypa/gh-action-pypi-publish@717ba43cfbb0387f6ce311b169a825772f54d295
        with:
          repository_url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}

      - name: Publish to PyPI
        if: ${{ github.event.action == 'published' }}
        uses: pypa/gh-action-pypi-publish@717ba43cfbb0387f6ce311b169a825772f54d295
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
