name: tox-test

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
  workflow_dispatch:
  schedule:
    # Schedule every Saturday at 00:30 UTC
    - cron: '30 0 * * 6'

jobs:
  python-ci:
    uses: epsy/python-workflows/.github/python-ci
    with:
    secrets:
      delegate_github_token: ${{ secrets.GITHUB_TOKEN }}
